version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: task-management-node-server
    command: /usr/src/app/node_modules/.bin/nodemon index.js
    volumes:
      - "./server:/server"
    ports:
      - "8000:8000"


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: task-management-react-client
    command: npm start
    volumes:
      - "./client:/client"
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
